version: '3'

services:
  jupyter:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: llm-engineering
    environment:
      - 'JUPYTER_TOKEN=docker'
      - 'EDITOR=code --wait'
      - 'HISTFILE=/root/bash_history/.bash_history'
      - 'SOURCE_PATH=${PWD}'
    ports:
      - 8888:8888
    volumes:
      - bash_history:/root/bash_history

volumes:
  bash_history: